version: "3.8"

services:
  frontend:
    build:
      context: react
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:3000"
    networks:
      - backend_default
  # nginx:
  #   build: nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #   networks:
  #     - app-network

networks:
  backend_default:
    external: true
