stages:
  - build
  - deploy

build:
  image: node:20
  stage: build
  script:
    - npm install
    - npm run build
    - npm run export
  artifacts:
    paths:
      - out

pages:
  image: node:20
  stage: deploy
  dependencies:
    - build
  script:
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - testFront
