pages:
  stage: deploy
  image: alpine:latest
  script:
    - mkdir -p public
    - find . -mindepth 1 -maxdepth 1 ! -name public -exec cp -r {} public/ \;
  artifacts:
    paths:
      - public
  only:
    - testFront
