stages:
  - build
  - test
  - deploy

test_ssh:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/test_key
    - chmod 600 ~/.ssh/test_key
    - ssh -i ~/.ssh/test_key root@85.198.81.168 "echo 'SSH success!'"