version: "3.8"

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: vcddbname
      POSTGRES_USER: vcddbuser
      POSTGRES_PASSWORD: vcddbpassword
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vcddbuser -d vcddbname" ]
      interval: 3s
      timeout: 3s
      retries: 5

  database-service:
    build: ./Database_service
    ports:
      - "8082:8080"
    depends_on:
      database:
        condition: service_healthy

  auth-service:
    build: ./Authentication_service
    ports:
      - "8081:8080"
    depends_on:
      database:
        condition: service_healthy
      database-service:
        condition: service_started

  api-service:
    build: ./API_service
    ports:
      - "80:8080"
    depends_on:
      database:
        condition: service_healthy
      auth-service:
        condition: service_started
      database-service:
        condition: service_started
